name: graphql_2_rest
description: A lightweight library for converting GraphQL queries into REST format, enabling the use of any HTTP client for executing requests.
version: 2.0.0
homepage: https://github.com/ihorbokov/graphql_2_rest

environment:
  sdk: '>=2.15.0 <4.0.0'

dev_dependencies:
  very_good_analysis: ^6.0.0