name: graphql_2_rest
description: A simple way to convert GraphQL queries to REST in order to use any HTTP client for performing a request.
version: 1.0.7
homepage: https://github.com/phimary/graphql_2_rest

environment:
  sdk: '>=2.12.0 <4.0.0'

dev_dependencies:
  very_good_analysis: ^5.1.0